server:
  port: 8081

spring:
  application:
    name: portal-server
  redis:
    host: localhost
    port: 6379
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
      config:
        server-addr: localhost:8848
        file-extension: yaml

mybatis-plus:
  mapper-locations: classpath*:/mapper/**/*.xml

portal:
  security:
    allowedHosts: []
  sso:
    ticketTtlSeconds: 60
  ptk:
    ttlSeconds: 600
  userAuth:
    cacheTtlSeconds: 600
  events:
    streamKey: portal:events

auth:
  serverBaseUrl: http://localhost:8080
  internalToken: change-me
