server:
  port: 8080

spring:
  application:
    name: auth-server
  redis:
    host: localhost
    port: 6379

sa-token:
  token-name: satoken
  is-read-cookie: true
  is-write-cookie: true
  cookie:
    http-only: true

auth:
  internalToken: "change-me"
